name: Build package on PR opening

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - develop
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Use Node.js
    uses: actions/setup-node@v2
    with:
      node-version: "20"

  - name: Install dependencies
    run: npm install

  - name: Run pre-commit script
    run: npm run pre-commit
